config/routes.rb
ProjectTracker::Application.routes.draw do

  devise_for :people

  get "home/index"

  resources :people do
    resources :messages
  end

  resources :projects do
    resources :stories do
      post "assign"
      post "change_status"
    end

    post "addCollaborator"
    get "removeCollaborator"
  end

  root :to => "projects#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :person

  def changeStatus
    self.status = "read"
    self.save
  end

end



# == Schema Information
#
# Table name: messages
#
#  id         :integer         not null, primary key
#  content    :string(255)
#  status     :string(255)
#  created_at :datetime
#  updated_at :datetime
#  person_id  :integer
#  project_id :integer
#  story_id   :integer
#

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_person!

  def index
    @person = current_person
    @messages = @person.messages.order("created_at DESC")
  end

  def destroy
    @person = Person.find(params[:person_id])
    @message = @person.messages.find(params[:id])
    if @message.destroy
      redirect_to person_messages_path(@person), :notice => "Message Deleted Successfully"
    else
      redirect_to person_messages_path(@person), :alert => "Oops! Delete Unsuccessfull, try Again"
    end
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
%h2 Message List
- @messages.each do |message|
  #message_list
    = message.content
    = "#{time_ago_in_words(message.created_at)} ago! "
    %br
    = "Now Goto this "
    = link_to "Project", project_path(message.project_id)
    = " or "
    = link_to "Story", project_story_path(message.project_id, message.story_id)
    %em.new_message
      = "New Message" if message.status == "unread"
    = link_to image_tag("delete_icon.gif"), person_message_path(current_person.id, message), :title => "Click to Delete", :id => "Delete", :confirm => "Sure, wanna delete?", :method => :delete
    %br

- @messages.each do |message|
  - message.changeStatus

app/views/messages/show.html.haml
%h1 Messages#show
%p Find me in app/views/messages/show.html.haml