config/routes.rb
ProjectTracker::Application.routes.draw do

  devise_for :people

  get "home/index"

  resources :people do
    resources :messages
  end

  resources :projects do
    resources :stories do
      post "assign"
      post "change_status"
    end

    post "addCollaborator"
    get "removeCollaborator"
  end

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :stories, :dependent => :destroy
  has_many :people, :through => :connections

  validates :title, :presence => true
  validates :description, :presence => true

  # def setDefaults
  #    self.points = 0
  #  end
end



# == Schema Information
#
# Table name: projects
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  points      :integer         default(0)
#  person_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_person!

  def index
    if params[:search]
       @projects = Project.find(:all, :conditions => ['title LIKE ?', "%#{params[:search]}%"])
    else
      @projects = current_person_project
    end
  end

  def show
    @all_people = Person.all
    @project = Project.find(params[:id])
    @stories = @project.stories
    @owner = Person.find(@project.person_id)
    @collaborators = Connection.find(:all, :conditions => ['project_id = ?', params[:id] ])
  end

  def create
    @project = Project.new(params[:project])
    @project.person_id = current_person.id
    if @project.save
      Connection.create(:project_id => @project.id, :person_id => current_person.id, :types => "owner")
      redirect_to projects_path, :notice => "Project Added Successfully"
    else
      render :action => "new", :alert => "Project Add Failed!!"
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to(projects_path, :notice => "Project Updated Successfully")
    else
      render :action => "edit", :alert => "Project Update Failure!!"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    Connection.where("project_id = ?", @project.id).delete_all
    if @project.destroy
      redirect_to projects_path, :notice => "Project Deleted Successfully"
    else
      redirect_to projects_path, :alert => "Project Deletion Failed!!"
    end
  end

  def addCollaborator
    @project = Project.find(params[:project_id])
    @person = Person.find(params[:people])
    if Connection.find_or_create_by_person_id_and_project_id(:person_id => @person.id, :project_id => @project.id, :types => "collaborator")
      redirect_to project_path(@project), :notice => " #{@person.name} is now added to #{@project.title}"
    else
      redirect_to project_path(@project), :notice => " Unable to add #{@person.name} to #{@project.title}"
    end
  end

  def removeCollaborator
    @project = Project.find(params[:project_id])
    @person = Person.find(params[:person_id])
    if Connection.delete_all(:project_id => @project.id, :person_id => @person.id)
      redirect_to project_path(@project), :alert => " #{@person.name} is now removed from #{@project.title}"
    else
      redirect_to project_path(@project), :alert => " Unable to remove #{@person.name} from #{@project.title}"
    end
  end

  def current_person_project
    project = []
    Connection.find(:all, :order => 'id DESC', :conditions => [ "person_id = ? ", current_person.id ]).each do |connection|
      project << Project.find(connection.project_id)
    end
    return project
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def connected_people(connections)
    @people = Array.new
    connections.each do |obj|
      @people.push(Person.find(obj.person_id))
    end
    @people
  end

  def calculate_points(project)
    points = 0
    project.stories.each do |story|
      story.status == "Accepted" ? points += story.weight : points += 0
    end
    return points
  end

end

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |form| %>
    <%= form.inputs do %>
            <%= form.input :title %>
            <%= form.input :description, :input_html => {:rows => 12, :maxlength => 400 } %>
        <% end %>
        <%= form.buttons do %>
            <%= form.commit_button %>
        <% end %>
<% end %>

app/views/projects/edit.html.haml
- if is_owner(@project)
  %h1 Edit Project
  %br
  = render 'form'
- else
  = "Sorry! Unauthorized Access!"

app/views/projects/index.html.haml
#project_index_header
  %span#my_projects_title My Projects
  %span#add_project
    = link_to image_tag('add.gif', :alt => 'Add new Project') + "Add Project", new_project_path, :id => "Add Project", :title => "Add new Project"

#my_projects
  - @projects.each do |project|
    .project_list
      = link_to "#{project.title}", project_path(project)
      - points = calculate_points(project)
      = pluralize(points, "point")
      -if is_owner(project)
        =link_to image_tag("edit_icon.gif", :alt => "Click to Edit"), edit_project_path(project), :id => "Edit", :title => "Click to Edit"
        =link_to image_tag("delete_icon.gif"), project_path(project), :title => "Click to Delete", :id => "Delete", :confirm => "Sure, wanna delete?", :method => :delete
      %br

app/views/projects/new.html.haml
%h2 Add New Projects
%br
= render "form"

app/views/projects/show.html.haml
%h2
  = "#{@project.title} ("
  - points = calculate_points(@project)
  = pluralize("#{points}","point")
  = ")"
%br
= "#{@project.description}"
%br
%br
#stories_header
  %span#stories_title Stories
  %span#add_story
    - if is_owner(@project)
      = link_to image_tag('add.gif', :alt => 'Add new Story') + "Add Story", new_project_story_path(@project), :id => "Add Story", :title => "Add new Story"

#stories_list
  - if @stories.each.count < 1
    %em
      = "No Stories Yet!"

  - @stories.each do |story|
    .story_list
      = link_to "#{story.title}", project_story_path(@project, story)

      = "owned by #{@owner.name} has "

      = pluralize(story.weight, "point")

      - if is_owner(@project)
        = link_to image_tag("edit_icon.gif", :alt => "Click to Edit"), edit_project_story_path(@project, story), :id => "Edit", :title => "Click to Edit"
        = link_to image_tag("delete_icon.gif"), project_story_path(@project, story), :title => "Click to Delete", :id => "Delete", :confirm => "Sure, wanna delete?", :method => :delete

#people_project
  = render "shared/connected_people"