config/routes.rb
ProjectTracker::Application.routes.draw do

  devise_for :people

  get "home/index"

  resources :people do
    resources :messages
  end

  resources :projects do
    resources :stories do
      post "assign"
      post "change_status"
    end

    post "addCollaborator"
    get "removeCollaborator"
  end

  root :to => "projects#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  belongs_to :person

  validates :weight, :presence => true, :numericality => true
  validates :title, :presence => true, :uniqueness => true

  def setDefaults
    self.status = "Not Yet Started"
  end
end


# == Schema Information
#
# Table name: stories
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :string(255)
#  project_id  :integer
#  weight      :integer
#  person_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  status      :string(255)
#

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_person!

  def new
    @project = Project.find(params[:project_id])
    @story = @project.stories.new
  end

  def show
    @story = Story.find(params[:id])
    @project = Project.find(params[:project_id])
    @people = find_people_in_this_project(@project)
  end

   def edit
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
     redirect_to(project_path(@project), :notice => "Story Updated Successfully")
    else
      render :action => "edit", :alert => "Story Update Failure!!"
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @story = @project.stories.new(params[:story])
    if @story.save
      redirect_to project_path(@project), :notice => "Story Created Successfully"
    else
      render :action => "new", :alert => "Oops! Unable to create Story"
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if @story.destroy
       redirect_to project_path(@project), :notice => "Story Deleted Successfully"
    else
       redirect_to project_path(@project), :alert => "Story Deletion Failed!!"
    end
  end

  def assign
    @story = Story.find(params[:story_id])
    @project = Project.find(params[:project_id])
    @person = Person.find(params[:people])
    @story.update_attributes(:person_id => @person.id)
    send_assign_message(@story, @project, @person)
    redirect_to project_story_path(@project, @story)
  end

  def change_status
    @story = Story.find(params[:story_id])
    @project = Project.find(params[:project_id])
    @story.update_attributes(:status => params[:status])
    send_status_change_msg(@project, @story, params[:status])
    redirect_to project_story_path(@project,@story)
  end

end

app/helpers/stories_helper.rb
module StoriesHelper

  def getName(id)
    Person.find(id).name
  end

end

app/views/stories/_assign_story_form.html.erb
<%= form_tag (project_story_assign_path(@project,@story)) do %>
  <%= select_tag "people", options_from_collection_for_select(@people, "id", "name") %>
  <%= submit_tag "Assign" %>
<% end %>

app/views/stories/_form.html.erb
<%= semantic_form_for ([@project, @story]) do |form| %>
    <%= form.inputs do %>
            <%= form.input :title %>
            <%= form.input :description, :as => :text, :input_html => { :rows => 5, :maxlength => 254 } %>
            <%= form.input :weight %>
        <% end %>
        <%= form.buttons do %>
            <%= form.commit_button %>
        <% end %>
<% end %>

app/views/stories/_status_change_form.html.erb
<%= form_tag (project_story_change_status_path(@project,@story)) do %>
  <% if is_owner(@project) %>
    <%= select_tag "status", options_for_select([ ["Accepted"],["Rejected"] ]) %>
  <% elsif is_authorized(@story) %>
    <%= select_tag "status", options_for_select([ ["Working"],["Finished"] ]) %>
  <% end %>
  <%= submit_tag "Change Status" %>
<% end %>

app/views/stories/create.html.haml
%h1 Stories#create
%p Find me in app/views/stories/create.html.haml

app/views/stories/edit.html.haml
- if is_owner(@project)
  %h1 Edit Story
  %br
  = render 'form'
- else
  = "Sorry! Unauthorized Access!"

app/views/stories/index.html.haml
%h1 Stories#index
%p Find me in app/views/stories/index.html.haml

app/views/stories/new.html.haml
- if is_owner(@project)
  %h2 Add New Story
  %br
  = render "form"
- else
  = "Sorry! Unauthorized Access!"

app/views/stories/show.html.haml
%h1
  = "Project: "
  = link_to @project.title, project_path(@project)
%h2
  = "Story: "
  = @story.title
= "Description: "
= @story.description
%br
%br
= "Status: "
= @story.status
%br
- if (is_owner(@project) or is_authorized(@story) and @story.person_id)
  .story_status_change= render "status_change_form"

%br
.assign_story
  = "Currently assigned to "
  - if @story.person_id
    = getName(@story.person_id)
  - else
    = "none"
  - if is_owner(@project)
    = render "assign_story_form"