config/routes.rb
ProjectTracker::Application.routes.draw do

  devise_for :people

  get "home/index"

  resources :people do
    resources :messages
  end

  resources :projects do
    resources :stories do
      post "assign"
      post "change_status"
    end

    post "addCollaborator"
    get "removeCollaborator"
  end

  root :to => "projects#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectTracker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'jquery-ui', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="head">
  <div id="head_cen">
    <div id="head_sup" class="head_pad">
      <p class="search">
        <div>
        <%= form_tag projects_path, :method => "get" do %>
          <%= text_field_tag :search, params[:search], :size => 15, :value => "Search Text Here" %>
          <%= submit_tag "Search", :name => nil%>
        <% end %>
        </div>
      <!--  <input name="search" type="text" class="txt" />
        <input name="search-btn" type="submit" class="btn" value="SEARCH" /> -->
        <span id="welcome_user">
          <% if person_signed_in? %>
              <%= " Welcome #{current_person.name}" %>
          <% end %>
        </span>
      </p>
      <h3>ProjectTracker</h3>
      <ul>
        <li><%= link_to "Home", projects_path %> </li>
            <% if person_signed_in? %>
                <% @count = Message.find(:all, :conditions => [ 'person_id = ? and status = ?', current_person.id, "unread" ]).count %>
                <li> <%= link_to "Message(#{@count} new)", person_messages_path(current_person) %> </li>
                <li> <%= link_to "LogOut", destroy_person_session_path %> </li>
            <% else %>
                <li><%= link_to "LogIn", new_person_session_path %></li>
            <% end %>
      </ul>
    </div>
  </div>
</div>
<div id="content">
  <div id="content_cen">
    <div id="content_sup" class="head_pad">
      <div id="welcom_pan">

        <div id="bread_crumb">
          <% if @project and @stories %>
            <%= link_to "Projects", projects_path %>
          <% elsif @story and @project %>
            <%= link_to "Projects", projects_path %> >>
            <%= link_to "#{@project.title}", project_path(@project) %>
          <% end %>
        </div>
      </div> <br />
      <div id="main_content">
        <p class="notice"><i><%= notice %></i></p>
        <p class="alert"><i><%= alert %></i></p>
        <%= yield %>
      </div>

    </div>
  </div>
</div>
<div id="foot">
  <div id="foot_cen">

    <p>&copy; Copyright Sprout Technology Services</p>
  </div>
</div>
</body>
</html>